### ISSUE TITLE
horepg hangs - possible cause: Build does not contain HTTP 500 error fix from upstream

### ISSUE THREAD

**Issue by ties** [LukasdeBoer/horepg-docker#2]
On my instance the horepg daemon often hangs partway through the EPG sync. This often happens while syncing regional channels and this prevents the wanted channels to be imported.

The upstream build of horepg includes a fix for HTTP 500 responses causing an error. I am trying out a new build of the container using horepg from upstream and this seems to work for now.

Changes:
```diff
diff --git a/Dockerfile b/Dockerfile
index 17b0aa6..acb7835 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -3,7 +3,7 @@ FROM python:alpine
 RUN apk update && apk upgrade && \
     apk add --no-cache bash git openssh

-RUN git clone https://github.com/LukasdeBoer/horepg.git /horepg && \
+RUN git clone https://github.com/beralt/horepg.git /horepg && \
     git clone https://github.com/eficode/wait-for.git /waitfor && \
     mv /waitfor/wait-for /usr/local/bin && \
     rm -rf /waitfor
```

**Comment by LukasdeBoer** [comment]
Thanks! I merged the upstream changes from beralt into my own repository and rebuilt the container.
